export const API_URL = 'http://127.0.0.1:5000';
export const APIKeyDesc = "The Application Programming Interface (API) key serves as an authenticator for the service.";
export const USVIPDesc = "The Unmanned Surface Vessel IP Address allows the system to communicate with the boat";
export const InUSVGPSDesc = "This is where the USV's GPS port is saved for navigation";
export const InUSVSonDesc = "This is where the USV's Sonar port is saved for underwater survellaince";
export const RDEipDesc = "Remote Data Endpoint IP is saved here";
export const someSettingdesc = "Never gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you";
export const someDrawingwayDesc = "This is the way we draw the things IDK how yet..."
export const sliderEGDesc  = "do we need this tooltip here?";
